parameters:
    sidus_eav_model.form.type.data.class: Sidus\EAVModelBundle\Form\Type\DataType
    sidus_eav_model.form.type.grouped_data.class: Sidus\EAVModelBundle\Form\Type\GroupedDataType
    sidus_eav_model.form.type.family_selector.class: Sidus\EAVModelBundle\Form\Type\FamilySelectorType
    sidus_eav_model.form.type.simple_data_selector.class: Sidus\EAVModelBundle\Form\Type\SimpleDataSelectorType

services:
    sidus_eav_model.form.type.data:
        class: '%sidus_eav_model.form.type.data.class%'
        arguments: ['@sidus_eav_model.family_configuration.handler', '%sidus_eav_model.entity.data.class%', '%sidus_eav_model.form.collection_type%']
        calls:
            - [setTranslator, ['@sidus_eav_model.translator']]
        tags:
            - { name: form.type, alias: sidus_data }

    sidus_eav_model.form.type.grouped_data:
        class: '%sidus_eav_model.form.type.grouped_data.class%'
        parent: 'sidus_eav_model.form.type.data'
        tags:
            - { name: form.type, alias: sidus_grouped_data }

    sidus_eav_model.form.type.family_selector:
        class: '%sidus_eav_model.form.type.family_selector.class%'
        arguments: ['@sidus_eav_model.family_configuration.handler']
        tags:
            - { name: form.type, alias: sidus_family_selector }

    sidus_eav_model.form.type.simple_data_selector:
        class: '%sidus_eav_model.form.type.simple_data_selector.class%'
        arguments: ['%sidus_eav_model.entity.data.class%']
        tags:
            - { name: form.type, alias: sidus_simple_data_selector }
